#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $PGUSER;
	CREATE ROLE $PGROLE;
	GRANT $PGROLE TO $PGUSER;
	CREATE DATABASE $PGDATABASE;
  GRANT ALL ON DATABASE $PGDATABASE TO $PGROLE;
EOSQL
