CREATE TABLE IF NOT EXISTS beer.cities(
   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(19) NOT NULL,
   state_id INTEGER NOT NULL references beer.states (id),
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);

SELECT beer.trigger_creation('beer','cities','tr_b_cities');

INSERT INTO beer.cities(name,state_id) VALUES ('Minneapolis',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Louisville',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Framingham',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Francisco',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Charleston',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bridgman',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Holland',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Grand Rapids',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Grand Rapids',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Petoskey',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Marquette',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Comstock Park',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('South Lyon',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Grand Rapids',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Indianapolis',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Evansville',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Indianapolis',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Plainfield',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Granger',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Martinsville',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Valparaiso',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Indianapolis',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Michigan City',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Indianapolis',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mishawaka',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Columbus',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bargersville',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seven Points',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chandler',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kansas City',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Stevens Point',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Torrance',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Francisco',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Buellton',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Dripping Springs',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kalamazoo',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Murphysboro',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('East Fairfield',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Export',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Manhattan',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Brooklyn',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hooksett',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Paso Robles',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Atlanta',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Troutville',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Roseville',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lombard',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lemont',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lyons',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bloomington',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('St. Paul',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portage',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Saint Louis',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Brooklyn Center',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Louisville',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Edwards',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Antonio',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('St Petersburg',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mt. Airy',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boone',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Charlotte',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Baltimore',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Detroit',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Madison',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Warrenville',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Duluth',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kalamazoo',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Francisco',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Sheridan',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fort Collins',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chico',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Houghton',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Traverse City',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Westerly',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kirkwood',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('East Windsor',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Wilkes-Barre',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cincinnati',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Athens',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cincinnati',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Dayton',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Marquette',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Morganton',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hershey',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cincinnati',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lexington',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Newport',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Anchorage',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lowell',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lone Tree',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Columbus',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pineland',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Eagle',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bloomfield',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('North Woodstock',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Vista',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Temecula',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Yardley',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Laurel',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Norfolk',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Conroe',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Durango',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Milwaukee',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cheboygan',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ashland',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ipswich',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Birmingham',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Houston',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Dallas',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Blanco',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('St Mary''s',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Wolcott',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Stevens Point',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Weston',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hattiesburg',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Monroe',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Dillon',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ada',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('St Paul',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Springdale',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tampa',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cold Spring',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Providence',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Loveland',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Nantucket',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hayward',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cleveland',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Arvada',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Raleigh',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Eugene',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Latrobe',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Baton Rouge',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Sisters',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Corvallis',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ashland',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lewisburg',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Phoenix',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Flagstaff',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Salt Lake City',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tempe',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fort Worth',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Traverse City',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Phoenixville',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lansdale',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Aurora',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Longmont',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('West Chester',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Windsor',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Garden City',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('White Salmon',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boonville',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Shelburne',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Brooklyn',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('New Orleans',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fort Worth',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Gary',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cambridge',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pittsboro',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Waynesville',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Nellysford',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Oklahoma City',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Columbus',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Spring Lake',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Paw Paw',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fredericksburg',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Springfield',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lincoln',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Jackson',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Middleton',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Oklahoma City',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bend',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Springfield',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bend',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Estacada',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bloomington',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hilo',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hilo',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lafayette',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Astoria',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Antonio',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kalona',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Evanston',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Verona',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Spearfish',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Farmers Branch',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Houston',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Richmond',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Atlanta',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cherry Hill',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ponderay',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bozeman',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Broomfield',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Odessa',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Atlantic Highlands',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Anchorage',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Middleburg Heights',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Temecula',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chatham',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Washington',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lake Geneva',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Rochester',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Gloucester',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tucson',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lake Havasu City',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Henderson',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boston',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bloomfield',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Charlottesville',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lexington',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Newburgh',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Memphis',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Los Angeles',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('College Station',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Plant City',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Stillwater',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Jackson',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Greenville',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Athens',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Stamford',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Southampton',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Angola',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tucson',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Santa Cruz',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Frankenmuth',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Somerset Center',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Baltimore',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('South Austin',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Minneapolis',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Rogers',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mount Pleasant',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Waterbury',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Baltimore',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Durango',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Albuquerque',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hyannis',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bridgewater Corners',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Shreveport',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Juneau',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ipswich',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Waterbury',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Charlottesville',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cleveland',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Middlebury',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Montauk',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Minneapolis',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('South Deerfield',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pawtucket',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mill Valley',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ridgefield Park',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kearney',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hays',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Milwaukee',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Port Clinton',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Gadsden',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Dallas',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Newport',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Idaho Springs',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lewiston',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Northamtpon',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Westminster',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pittsburgh',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('York',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Utica',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boston',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Danville',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Salt Lake City',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('South Burlington',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Canton',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Everett',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Virginia Beach',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Garden City',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tampa',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boise',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Francisco',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Woodinville',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Nashville',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Meridian',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bucryus',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Avon',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Wilmington',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Belfast',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Williamsburg',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Centralia',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Claremont',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lockland',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Meadville',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Black Mountain',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Croydon',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Saint Louis',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chicago',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Burlington',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bronx',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tulsa',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Morganton',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Albuquerque',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Diamond Springs',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Burlington',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fargo',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Missoula',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Papillion',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('St. John''s',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Worcester',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boynton Beach',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Palisade',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Brooklyn',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Richmond',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Abingdon',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Erie',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Santee',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Durham',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('South Bend',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Green Bay',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Luis Obispo',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Westfield',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Columbus',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bellingham',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bellingham',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Monument',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Philadelphia',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cleveland',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Shelbyville',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Charlotte',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fuquay-Varina',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lake Barrington',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pottstown',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Midvale',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Davenport',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mustang',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kent',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Francisco',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Buena Vista',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Carlsbad',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pottstown',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Conestoga',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Dunedin',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Astoria',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lahaina',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Midwest City',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Menominee',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Jacksonville',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Westerly',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lincoln',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Manheim',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Afton',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Crozet',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mt. Pleasant',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Paonia',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lexington',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Brevard',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Airway Heights',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Santa Fe',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Miami',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hudsonville',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Sacramento',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Douglas',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Moab',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Macon',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Washougal',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ann Arbor',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bend',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Eau Claire',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hamilton',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bend',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lakeside',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Woodbridge',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Huntsville',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Austin',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Arrington',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Savannah',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Biglerville',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Edwards',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Eugene',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Stevens Point',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denton',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Roanoke',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Saint Louis',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ashburn',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Slippery Rock',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Santa Cruz',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Asheville',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cincinnati',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Stratford',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Medford',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Brooklyn',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Traverse City',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kona',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Royal Oak',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fort Collins',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('O''Fallon',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Albuquerque',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Vadnais Heights',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lenoir',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Leominster',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Gainesville',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Half Moon Bay',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pacific',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Aurora',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Edwards',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Talkeetna',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bend',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hardy',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Menominie',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Sheridan',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Soldotna',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Denver',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('South San Francisco',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Golden',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Alpine',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Bend',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Jacksonville Beach',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Jacksonville',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tampa Bay',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Knoxville',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Athens',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Antonio',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Spirit Lake',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tacoma',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Minnetonka',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Marietta',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Redlands',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Sheffield',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Birmingham',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Halethorpe',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Telluride',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Gig Harbor',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Des Moines',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Yakima',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('New York',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Green Bay',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Woodinville',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Philadelphia',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Patchogue',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tampa',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Belmont',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Anchorage',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Silverton',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Newburyport',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Aurora',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Charlotte',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Glendale',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Stevensville',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Leavenworth',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Middlebury',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Portland',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lyons',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mooresville',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Krebs',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Fort Wayne',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lake Havasu City',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Cortland',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Tacoma',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Missoula',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Marlborough',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pawcatuck',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Colorado Springs',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('San Diego',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Greeley',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Carlsbad',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Myrtle Beach',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Chattanooga',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Boulder',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Frederick',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Santa Cruz',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Aspen',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Durham',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('New York',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Jacksonville',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Asheville',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Eau Claire',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Reno',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Dolores',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Smithton',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Abita Springs',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Mammoth Lakes',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Belt',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Williams',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Helena',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Rochester',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Greenville',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Kinston',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Battle Creek',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Hayward',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Whitefish',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Seattle',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Lancaster',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Elmira',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('North Conway',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Prescott',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Flagstaff',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Pinedale',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Silverton',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Libertyville',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Covington',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Wilson',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Ukiah',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Garrattsville',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('Anchorage',17) ON CONFLICT DO NOTHING;
