CREATE TABLE IF NOT EXISTS beer.cities(
   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(19) NOT NULL,
   state_id INTEGER references beer.states (id),
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);

SELECT beer.trigger_creation('beer','cities','tr_b_cities');

INSERT INTO beer.cities(name,state_id) VALUES ('minneapolis',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('louisville',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('framingham',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san francisco',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('charleston',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bridgman',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('holland',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('grand rapids',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('grand rapids',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('petoskey',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('marquette',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('comstock park',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('south lyon',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('grand rapids',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('indianapolis',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('evansville',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('indianapolis',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('plainfield',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('granger',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('martinsville',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('valparaiso',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('indianapolis',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('michigan city',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('indianapolis',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mishawaka',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('columbus',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bargersville',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seven points',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chandler',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kansas city',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('stevens point',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('torrance',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san francisco',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('buellton',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('dripping springs',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kalamazoo',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('murphysboro',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('east fairfield',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('export',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('manhattan',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('brooklyn',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hooksett',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('paso robles',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('atlanta',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('troutville',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('roseville',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lombard',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lemont',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lyons',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bloomington',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('st. paul',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portage',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('saint louis',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('brooklyn center',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('louisville',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('edwards',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san antonio',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('st petersburg',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mt. airy',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boone',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('charlotte',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('baltimore',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('detroit',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('madison',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('warrenville',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('duluth',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kalamazoo',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san francisco',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('sheridan',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fort collins',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chico',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('houghton',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('traverse city',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('westerly',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kirkwood',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('east windsor',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('wilkes-barre',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cincinnati',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('athens',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cincinnati',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('dayton',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('marquette',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('morganton',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hershey',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cincinnati',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lexington',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('newport',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('anchorage',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lowell',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lone tree',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('columbus',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pineland',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('eagle',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bloomfield',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('north woodstock',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('vista',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('temecula',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('yardley',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('laurel',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('norfolk',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('conroe',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('durango',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('milwaukee',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cheboygan',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ashland',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ipswich',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('birmingham',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('houston',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('dallas',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('blanco',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('st mary''s',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('wolcott',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('stevens point',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('weston',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hattiesburg',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('monroe',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('dillon',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ada',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('st paul',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('springdale',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tampa',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cold spring',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('providence',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('loveland',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('nantucket',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hayward',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cleveland',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('arvada',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('raleigh',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('eugene',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('latrobe',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('baton rouge',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('sisters',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('corvallis',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ashland',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lewisburg',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('phoenix',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('flagstaff',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('salt lake city',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tempe',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fort worth',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('traverse city',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('phoenixville',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lansdale',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('aurora',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('longmont',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('west chester',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('windsor',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('garden city',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('white salmon',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boonville',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('shelburne',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('brooklyn',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('new orleans',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fort worth',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('gary',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cambridge',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pittsboro',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('waynesville',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('nellysford',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('oklahoma city',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('columbus',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('spring lake',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('paw paw',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fredericksburg',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('springfield',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lincoln',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('jackson',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('middleton',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('oklahoma city',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bend',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('springfield',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bend',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('estacada',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bloomington',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hilo',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hilo',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lafayette',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('astoria',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san antonio',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kalona',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('evanston',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('verona',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('spearfish',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('farmers branch',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('houston',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('richmond',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('atlanta',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cherry hill',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ponderay',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bozeman',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('broomfield',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('odessa',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('atlantic highlands',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('anchorage',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('middleburg heights',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('temecula',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chatham',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('washington',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lake geneva',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('rochester',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('gloucester',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tucson',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lake havasu city',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('henderson',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boston',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bloomfield',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('charlottesville',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lexington',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('newburgh',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('memphis',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('los angeles',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('college station',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('plant city',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('stillwater',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('jackson',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('greenville',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('athens',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('stamford',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('southampton',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('angola',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tucson',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('santa cruz',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('frankenmuth',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('somerset center',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('baltimore',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('south austin',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('minneapolis',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('rogers',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mount pleasant',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('waterbury',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('baltimore',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('durango',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('albuquerque',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hyannis',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bridgewater corners',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('shreveport',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('juneau',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ipswich',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('waterbury',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('charlottesville',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cleveland',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('middlebury',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('montauk',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('minneapolis',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('south deerfield',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pawtucket',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mill valley',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ridgefield park',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kearney',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hays',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('milwaukee',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('port clinton',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('gadsden',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('dallas',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('newport',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('idaho springs',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lewiston',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('northamtpon',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('westminster',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pittsburgh',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('york',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('utica',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boston',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('danville',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('salt lake city',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('south burlington',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('canton',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('everett',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('virginia beach',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('garden city',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tampa',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boise',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san francisco',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('woodinville',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('nashville',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('meridian',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bucryus',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('avon',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('wilmington',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('belfast',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('williamsburg',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('centralia',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('claremont',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lockland',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('meadville',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('black mountain',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('croydon',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('saint louis',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chicago',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('burlington',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bronx',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tulsa',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('morganton',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('albuquerque',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('diamond springs',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('burlington',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fargo',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('missoula',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('papillion',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('st. john''s',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('worcester',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boynton beach',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('palisade',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('brooklyn',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('richmond',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('abingdon',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('erie',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('santee',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('durham',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('south bend',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('green bay',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san luis obispo',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('westfield',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('columbus',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bellingham',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bellingham',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('monument',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('philadelphia',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cleveland',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('shelbyville',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('charlotte',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fuquay-varina',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lake barrington',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pottstown',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('midvale',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('davenport',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mustang',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kent',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san francisco',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('buena vista',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('carlsbad',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pottstown',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('conestoga',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('dunedin',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('astoria',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lahaina',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('midwest city',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('menominee',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('jacksonville',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('westerly',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lincoln',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('manheim',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('afton',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('crozet',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mt. pleasant',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('paonia',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lexington',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('brevard',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('airway heights',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('santa fe',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('miami',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hudsonville',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('sacramento',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('douglas',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('moab',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('macon',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('washougal',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ann arbor',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bend',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('eau claire',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hamilton',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bend',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lakeside',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('woodbridge',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('huntsville',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('austin',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('arrington',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('savannah',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('biglerville',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('edwards',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('eugene',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('stevens point',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denton',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('roanoke',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('saint louis',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ashburn',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('slippery rock',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('santa cruz',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('asheville',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cincinnati',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('stratford',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('medford',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('brooklyn',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('traverse city',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kona',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('royal oak',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fort collins',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('o''fallon',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('albuquerque',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('vadnais heights',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lenoir',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('leominster',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('gainesville',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('half moon bay',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pacific',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('aurora',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('edwards',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('talkeetna',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bend',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hardy',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('menominie',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('sheridan',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('soldotna',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('denver',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('south san francisco',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('golden',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('alpine',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('bend',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('jacksonville beach',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('jacksonville',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tampa bay',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('knoxville',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('athens',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san antonio',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('spirit lake',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tacoma',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('minnetonka',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('marietta',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('redlands',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('sheffield',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('birmingham',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('halethorpe',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('telluride',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('gig harbor',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('des moines',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('yakima',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('new york',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('green bay',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('woodinville',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('philadelphia',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('patchogue',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tampa',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('belmont',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('anchorage',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('silverton',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('newburyport',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('aurora',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('charlotte',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('glendale',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('stevensville',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('leavenworth',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('middlebury',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('portland',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lyons',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mooresville',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('krebs',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('fort wayne',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lake havasu city',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('cortland',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('tacoma',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('missoula',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('marlborough',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pawcatuck',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('colorado springs',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('san diego',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('greeley',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('carlsbad',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('myrtle beach',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('chattanooga',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('boulder',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('frederick',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('santa cruz',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('aspen',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('durham',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('new york',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('jacksonville',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('asheville',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('eau claire',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('reno',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('dolores',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('smithton',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('abita springs',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('mammoth lakes',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('belt',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('williams',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('helena',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('rochester',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('greenville',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('kinston',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('battle creek',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('hayward',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('whitefish',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('seattle',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('lancaster',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('elmira',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('north conway',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('prescott',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('flagstaff',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('pinedale',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('silverton',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('libertyville',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('covington',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('wilson',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('ukiah',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('garrattsville',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(name,state_id) VALUES ('anchorage',17) ON CONFLICT DO NOTHING;
