CREATE TABLE IF NOT EXISTS beer.breweries(
   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   city_id INTEGER NOT NULL references beer.cities (id),
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);

SELECT beer.trigger_creation('beer','breweries','tr_b_breweries');

INSERT INTO beer.breweries(name,city_id) VALUES ('NorthGate Brewing',542) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Against the Grain Brewery',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Jack''s Abby Craft Lagers',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mike Hess Brewing Company',411) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fort Point Beer Company',251) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('COAST Brewing Company',415) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Great Divide Brewing Company',172) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tapistry Brewing',258) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Lake Brewing',391) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Mitten Brewing Company',83) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Brewery Vivant',294) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Petoskey Brewing',181) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blackrocks Brewery',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Perrin Brewing Company',214) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Witch''s Hat Brewing Company',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Founders Brewing Company',189) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Flat 12 Bierwerks',382) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tin Man Brewing Company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Black Acre Brewing Co.',196) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Brew Link Brewing',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bare Hands Brewery',279) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Three Pints Brewing',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Four Fathers Brewing',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Indiana City Brewing',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Burn ''Em Brewing',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sun King Brewing Company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Evil Czech Brewery',97) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('450 North Brewing Company',394) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Taxman Brewing Company',150) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cedar Creek Brewery',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('SanTan Brewing Company',230) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Boulevard Brewing Company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('James Page Brewing Company',325) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Dudes'' Brewing Company',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ballast Point Brewing Company',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Anchor Brewing Company',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Figueroa Mountain Brewing Company',539) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Avery Brewing Company',522) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Twisted X Brewing Company',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Gonzo''s BiggDogg Brewing',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Muddy Brewing',82) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lost Nation Brewing',373) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Rising Tide Brewing Company',520) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Rivertowne Brewing Company',184) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Revolution Brewing Company',263) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tallgrass Brewing Company',353) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sixpoint Craft Ales',122) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('White Birch Brewing',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Firestone Walker Brewing Company',76) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('SweetWater Brewing Company',511) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Flying Mouse Brewery',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Upslope Brewing Company',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pipeworks Brewing Company',103) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bent Brewstillery',362) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Flesk Brewing Company',440) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pollyanna Brewing Company',366) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('BuckleDown Brewing',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Destihl Brewery',98) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Summit Brewing Company',397) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Latitude 42 Brewing Company',128) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('4 Hands Brewing Company',111) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Surly Brewing Company',164) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Against The Grain Brewery',450) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Crazy Mountain Brewing Company',72) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('SlapShot Brewing Company',494) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mikerphone Brewing',318) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Freetail Brewing Company',418) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('3 Daughters Brewing',520) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Red Shedman Farm Brewery and Hop...',225) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Appalachian Mountain Brewery',172) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Birdsong Brewing Company',379) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Union Craft Brewing',136) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Atwater Brewery',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ale Asylum',407) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Two Brothers Brewing Company',93) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bent Paddle Brewing Company',453) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bell''s Brewery',519) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blue Owl Brewing',200) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Speakasy Ales & Lagers',298) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Black Tooth Brewing Company',81) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hopworks Urban Brewery',201) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Epic Brewing',395) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('New Belgium Brewing Company',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sierra Nevada Brewing Company',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Keweenaw Brewing Company',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Brewery Terra Firma',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Grey Sail Brewing Company',155) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Kirkwood Station Brewing Company',318) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Goose Island Brewing Company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Broad Brook Brewing LLC',463) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Lion Brewery',338) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Madtree Brewing Company',554) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Jackie O''s Pub & Brewery',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Rhinegeist Brewery',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Warped Wing Brewing Company',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blackrocks Brewery',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Catawba Valley Brewing Company',158) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tröegs Brewing Company',191) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mission Brewery',478) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Christian Moerlein Brewing Company',473) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('West Sixth Brewing',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Coastal Extreme Brewing Company',288) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('King Street Brewing Company',177) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Beer Works Brewery',364) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lone Tree Brewing Company',310) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Four String Brewing Company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Glabrous Brewing Company',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bonfire Brewing Company',435) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Thomas Hooker Brewing Company',160) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Woodstock Inn, Station & Brewery',130) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Renegade Brewing Company',86) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mother Earth Brew Company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Black Market Brewing Company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Vault Brewing Company',508) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Jailbreak Brewing Company',503) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Smartmouth Brewing Company',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Base Camp Brewing Co.',91) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Alameda Brewing',509) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Southern Star Brewing Company',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Steamworks Brewing Company',146) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Horny Goat Brew Pub',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cheboygan Brewing Company',83) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Center of the Universe Brewing C...',75) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ipswich Ale Brewery',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Griffin Claw Brewing Company',149) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Karbach Brewing Company',336) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Uncle Billy''s Brewery and Smokeh...',333) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Deep Ellum Brewing Company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Real Ale Brewing Company',268) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Straub Brewery',129) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Shebeen Brewing Company',179) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Stevens Point Brewery',390) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Weston Brewing Company',163) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Southern Prohibition Brewing Com...',544) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Minhas Craft Brewery',238) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pug Ryan''s Brewery',344) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hops & Grains Brewing Company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sietsema Orchards and Cider Mill',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Summit Brewing Company',357) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Core Brewing & Distilling Company',220) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Independence Brewing Company',145) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cigar City Brewing Company',179) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Third Street Brewhouse',65) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Narragansett Brewing Company',455) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Grimm Brothers Brewhouse',436) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cisco Brewers',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Angry Minnow',339) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Platform Beer Company',300) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Odyssey Beerwerks',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lonerider Brewing Company',173) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Oakshire Brewing',525) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fort Pitt Brewing Company',209) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tin Roof Brewing Company',536) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Three Creeks Brewing',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('2 Towns Ciderhouse',105) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Caldera Brewing Company',175) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Greenbrier Valley Brewing Company',341) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Phoenix Ale Brewery',137) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lumberyard Brewing Company',53) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Uinta Brewing Company',219) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Four Peaks Brewing Company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Martin House Brewing Company',103) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Right Brain Brewery',248) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sly Fox Brewing Company',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Round Guys Brewing',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Great Crescent Brewery',454) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Oskar Blues Brewery',57) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Boxcar Brewing Company',186) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('High Hops Brewery',117) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Crooked Fence Brewing Company',126) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Everybody''s Brewing',453) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Anderson Valley Brewing Company',360) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fiddlehead Brewing Company',73) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Evil Twin Brewing',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('New Orleans Lager & Ale Brewing ...',440) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Spiteful Brewing Company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Rahr & Sons Brewing Company',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('18th Street Brewery',547) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cambridge Brewing Company',95) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Carolina Brewery',109) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Frog Level Brewing Company',417) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wild Wolf Brewing Company',199) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('COOP Ale Works',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Seventh Son Brewing Company',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Oasis Texas Brewing Company',345) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Vander Mill Ciders',421) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('St. Julian Winery',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pedernales Brewing Company',180) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mother''s Brewing',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Modern Monks Brewery',213) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Two beer Brewing Company',548) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Snake River Brewing Company',302) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Capital Brewery',205) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Anthem Brewing Company',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Goodlife Brewing Co.',495) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Breakside Brewery',56) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Goose Island Brewery Company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Burnside Brewing Co.',469) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hop Valley Brewing Company',99) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Worthy Brewing Company',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Occidental Brewing Company',377) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fearless Brewing Company',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Upland Brewing Company',502) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mehana Brewing Co.',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hawai''i Nui Brewing Co.',117) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('People''s Brewing Company',267) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fort George Brewery',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Branchline Brewing Company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Kalona Brewing Company',522) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Modern Times Beer',158) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Temperance Beer Company',230) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wisconsin Brewing Company',245) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Crow Peak Brewing Company',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Grapevine Craft Brewery',317) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Buffalo Bayou Brewing Company',115) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Texian Brewing Co.',260) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Orpheus Brewing',167) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Forgotten Boardwalk',290) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Laughing Dog Brewing Company',252) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bozeman Brewing Company',351) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Choice Brewing',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Storm Brewing Company',438) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Carton Brewing Company',226) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Midnight Sun Brewing Company',484) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fat Head''s Brewery',67) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Refuge Brewery',186) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Chatham Brewing',472) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('DC Brau Brewing Company',240) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Geneva Lake Brewing Company',290) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Rochester Mills Brewing Company',237) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cape Ann Brewing Company',159) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Borderlands Brewing Company',224) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('College Street Brewhouse and Pub',168) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Joseph James Brewing Company',287) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Harpoon Brewery',224) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Back East Brewing Company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Champion Brewing Company',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Devil''s Backbone Brewing Company',481) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Newburgh Brewing Company',444) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wiseacre Brewing Company',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Golden Road Brewing',401) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('New Republic Brewing Company',161) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Infamous Brewing Company',412) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Two Henrys Brewing Company',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lift Bridge Brewing Company',141) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lucky Town Brewing Company',142) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Quest Brewing Company',187) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Creature Comforts',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Half Full Brewery',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Southampton Publick House',394) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Chapman''s Brewing',116) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Barrio Brewing Company',240) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Santa Cruz Mountain Brewing',549) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Frankenmuth Brewery',527) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Meckley''s Cidery',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Stillwater Artisanal Ales',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Finch''s Beer Company',525) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('South Austin Brewery',105) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bauhaus Brew Labs',169) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ozark Beer Company',553) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mountain Town Brewing Company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Otter Creek Brewing',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Brewer''s Art',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Denver Beer Company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ska Brewing Company',540) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tractor Brewing Company',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Peak Organic Brewing Company',478) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cape Cod Beer',392) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Long Trail Brewing Company',231) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Great Raft Brewing Company',396) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Alaskan Brewing Company',364) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Notch Brewing Company',107) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Alchemist',326) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Three Notch''d Brewing Company',82) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Portside Brewery',145) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Otter Creek Brewing',386) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Montauk Brewing Company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Indeed Brewing Company',139) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Berkshire Brewing Company',314) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Foolproof Brewing Company',152) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Headlands Brewing Company',365) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bolero Snort Brewery',106) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Thunderhead Brewing Company',404) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Defiance Brewing Company',284) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Milwaukee Brewing Company',84) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Catawba Island Brewing',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Back Forty Beer Company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Four Corners Brewing Company',60) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Saint Archer Brewery',271) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Rogue Ales',371) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hale''s Ales',554) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tommyknocker Brewery',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Baxter Brewing Company',146) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Northampton Brewery',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Black Shirt Brewing Company',211) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wachusett Brewing Company',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Widmer Brothers Brewing Company',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hop Farm Brewing Company',426) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Liquid Hero Brewery',265) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Matt Brewing Company',502) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Boston Beer Company',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Old Forge Brewing Company',346) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Utah Brewers Cooperative',152) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Magic Hat Brewing Company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blue Hills Brewery',464) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Night Shift Brewing',555) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Beach Brewing Company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Payette Brewing Company',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Brew Bus Brewing',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sockeye Brewing Company',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pine Street Brewery',109) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dirty Bucket Brewing Company',390) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Jackalope Brewing Company',543) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Slanted Rock Brewing Company',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Piney River Brewing Company',477) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cutters Brewing Company',488) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Iron Hill Brewery & Restaurant',259) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Marshall Wharf Brewing Company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Banner Beer Company',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dick''s Brewing Company',68) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Claremont Craft Ales',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Rivertown Brewing Company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Voodoo Brewery',189) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('D.L. Geary Brewing Company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pisgah Brewing Company',108) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Neshaminy Creek Brewing Company',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Morgan Street Brewery',250) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Half Acre Beer Company',395) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Just Beer Project',300) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Bronx Brewery',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dead Armadillo Craft Brewing',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Catawba Brewing Company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('La Cumbre Brewing Company',212) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('David''s Ale Works',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Traveler Beer Company',58) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fargo Brewing Company',143) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Sky Brewing Company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Nebraska Brewing Company',475) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Uncle John''s Fruit House Winery',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wormtown Brewery',171) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Due South Brewing Company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Palisade Brewing Company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('KelSo Beer Company',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hardywood Park Craft Brewery',487) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wolf Hills Brewing Company',292) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lavery Brewing Company',62) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Manzanita Brewing Company',369) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fullsteam Brewery',273) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Four Horsemen Brewing Company',346) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hinterland Brewery',469) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Central Coast Brewing Company',344) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Westfield River Brewing Company',536) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Elevator Brewing Company',320) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Aslan Brewing Company',317) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Kulshan Brewery',86) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pikes Peak Brewing Company',155) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Manayunk Brewing Company',211) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Buckeye Brewing',207) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Daredevil Brewing Company',551) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('NoDa Brewing Company',238) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Aviator Brewing Company',498) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wild Onion Brewing Company',326) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hilliard''s Beer',125) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mikkeller',463) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bohemian Brewery',500) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Great River Brewery',480) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mustang Brewing Company',529) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Airways Brewing Company',101) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('21st Amendment Brewery',387) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Eddyline Brewery & Restaurant',320) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pizza Port Brewing Company',473) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sly Fox Brewing Company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Spring House Brewing Company',297) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('7venth Sun',465) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Astoria Brewing Company',403) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Maui Brewing Company',104) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('RoughTail Brewing Company',376) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lucette Brewing Company',373) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bold City Brewery',107) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Grey Sail Brewing of Rhode Island',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blue Blood Brewing Company',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Swashbuckler Brewing Company',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blue Mountain Brewery',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Starr Hill Brewery',213) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Westbrook Brewing Company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Shipyard Brewing Company',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Revolution Brewing',504) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Natian Brewery',174) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Alltech''s Lexington Brewing Company',270) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Oskar Blues Brewery (North Carol...',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Orlison Brewing Company',73) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Breckenridge Brewery',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Santa Fe Brewing Company',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Miami Brewing Company',219) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Schilling & Company',333) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hops & Grain Brewery',399) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('White Flame Brewing Company',266) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ruhstaller Beer Company',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Saugatuck Brewing Company',331) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Moab Brewery',303) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Macon Beer Company',356) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Amnesia Brewing Company',255) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wolverine State Brewing Company',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Red Tank Cider Company',175) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cascadia Ciderworks United',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fate Brewing Company',93) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lazy Monk Brewing',335) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bitter Root Brewing',201) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('10 Barrel Brewing Company',460) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tamarack Brewing Company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('New England Brewing Company',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Seattle Cider Company',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Straight to Ale',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Austin Beerworks',256) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blue Mountain Brewery',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Coastal Empire Beer Company',514) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Jack''s Hard Cider (Hauser Estate...',120) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Boulder Beer Company',497) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Coalition Brewing Company',405) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sanitas Brewing Company',112) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Gore Range Brewery',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Redstone Meadery',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blue Dog Mead',288) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hess Brewing Company',456) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wynkoop Brewing Company',496) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ciderboys',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Armadillo Ale Works',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Roanoke Railhouse Brewery',534) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Schlafly Brewing Company',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Asher Brewing Company',456) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lost Rhino Brewing Company',363) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('North Country Brewing Company',460) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Seabright Brewery',125) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('French Broad Brewery',220) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Angry Orchard Cider Company',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Two Roads Brewing Company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Southern Oregon Brewing Company',248) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Brooklyn Brewery',388) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Right Brain Brewery',454) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Kona Brewing Company',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('MillKing It Productions',485) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pateros Creek Brewing Company',505) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('O''Fallon Brewery',386) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Marble Brewery',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Wood Brewery',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Howard Brewing Company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Downeast Cider House',165) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Swamp Head Brewery',486) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mavericks Beer Company',259) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('TailGate Beer',261) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Northwest Brewing Company',176) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dad & Dude''s Breweria',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Centennial Beer Company',435) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Denali Brewing Company',257) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Deschutes Brewery',162) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sunken City Brewing Company',273) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lucette Brewing Company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Black Tooth Brewing Company',137) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Kenai River Brewing Company',116) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('River North Brewery',277) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Fremont Brewing Company',267) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Armstrong Brewing Company',485) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('AC Golden Brewing Company',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Bend Brewing Company',303) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Good Life Brewing Company',265) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Engine 15 Brewing',112) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Green Room Brewing',180) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Brindle Dog Brewing Company',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Peace Tree Brewing Company',218) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Terrapin Brewing Company',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pete''s Brewing Company',244) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Okoboji Brewing Company',324) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Crystal Springs Brewing Company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Engine House 9',99) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tonka Beer Company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Red Hare Brewing Company',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Hangar 24 Craft Brewery',314) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big Elm Brewing',163) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Good People Brewing Company',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Heavy Seas Beer',407) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Telluride Brewing Company',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('7 Seas Brewing Company',400) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Confluence Brewing Company',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bale Breaker Brewing Company',488) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('The Manhattan Brewing Company',87) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('MacTarnahans Brewing Company',142) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Stillmank Beer Company',208) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Redhook Brewery',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dock Street Brewery',160) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Blue Point Brewing Company',439) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Tampa Bay Brewing Company',59) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Devil''s Canyon Brewery',79) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Stone Coast Brewing Company',271) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Broken Tooth Brewing Company',275) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Seven Brides Brewery',495) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Newburyport Brewing Company',256) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dry Dock Brewing Company',347) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cans Bar and Canteen',162) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sprecher Brewing Company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wildwood Brewing Company',337) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('High Noon Saloon And Brewery',352) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Woodchuck Hard Cider',450) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sea Dog Brewing Company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Oskar Blues Brewery',549) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Carolina Beer & Beverage',77) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Krebs Brewing Company (Pete''s Pl...',114) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Warbird Brewing Company',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mudshark Brewing Company',280) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Spilker Ales',178) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wingman Brewers',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Kettle House Brewing Company',430) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sherwood Forest Brewers',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Cottrell Brewing',426) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Arctic Craft Brewery',434) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Monkey Paw Pub & Brewery',383) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Crabtree Brewing Company',368) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Emerald City Beer Company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Butcher''s Brewing',301) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('New South Brewing Company',262) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Big River Brewing Company',74) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Twisted Pine Brewing Company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Flying Dog Brewery',188) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Uncommon Brewers',58) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Aspen Brewing Company',57) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Triangle Brewing Company',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Bomb Beer Company',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Churchkey Can Company',399) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Intuition Ale Works',518) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Asheville Brewing Company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Northwoods Brewpub',433) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Buckbean Brewing Company',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dolores River Brewery',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Flat Rock Brewing Company',506) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Abita Brewing Company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mammoth Brewing Company',349) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Harvest Moon Brewing Company',81) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Grand Canyon Brewing Company',297) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lewis and Clark Brewing Company',448) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dundee Brewing Company',324) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Twin Lakes Brewing Company',294) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mother Earth Brewing Company',438) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Arcadia Brewing Company',205) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Angry Minnow Brewing Company',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Great Northern Brewing Company',521) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Pyramid Breweries',177) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Lancaster Brewing Company',411) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Upstate Brewing Company',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Moat Mountain Smoke House & Brew...',431) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Prescott Brewing Company',512) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mogollon Brewing Company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Wind River Brewing Company',388) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Silverton Brewery',472) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Mickey Finn''s Brewery',427) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Covington Brewhouse',461) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Dave''s Brewfarm',74) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Ukiah Brewing Company',511) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Butternuts Beer and Ale',268) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('Sleeping Lady Brewing Company',7) ON CONFLICT DO NOTHING;
