CREATE TABLE IF NOT EXISTS beer.breweries(
   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   city_id INTEGER NOT NULL references beer.cities (id),
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);

SELECT beer.trigger_creation('beer','breweries','tr_b_breweries');

INSERT INTO beer.breweries(name,city_id) VALUES ('northgate brewing',542) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('against the grain brewery',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('jack''s abby craft lagers',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mike hess brewing company',411) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fort point beer company',251) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('coast brewing company',415) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('great divide brewing company',172) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tapistry brewing',258) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big lake brewing',391) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the mitten brewing company',83) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('brewery vivant',294) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('petoskey brewing',181) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blackrocks brewery',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('perrin brewing company',214) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('witch''s hat brewing company',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('founders brewing company',189) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('flat 12 bierwerks',382) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tin man brewing company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('black acre brewing co.',196) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('brew link brewing',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bare hands brewery',279) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('three pints brewing',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('four fathers brewing',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('indiana city brewing',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('burn ''em brewing',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sun king brewing company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('evil czech brewery',97) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('450 north brewing company',394) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('taxman brewing company',150) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cedar creek brewery',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('santan brewing company',230) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('boulevard brewing company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('james page brewing company',325) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the dudes'' brewing company',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ballast point brewing company',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('anchor brewing company',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('figueroa mountain brewing company',539) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('avery brewing company',522) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('twisted x brewing company',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('gonzo''s biggdogg brewing',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big muddy brewing',82) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lost nation brewing',373) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('rising tide brewing company',520) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('rivertowne brewing company',184) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('revolution brewing company',263) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tallgrass brewing company',353) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sixpoint craft ales',122) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('white birch brewing',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('firestone walker brewing company',76) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sweetwater brewing company',511) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('flying mouse brewery',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('upslope brewing company',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pipeworks brewing company',103) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bent brewstillery',362) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('flesk brewing company',440) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pollyanna brewing company',366) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('buckledown brewing',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('destihl brewery',98) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('summit brewing company',397) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('latitude 42 brewing company',128) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('4 hands brewing company',111) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('surly brewing company',164) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('against the grain brewery',450) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('crazy mountain brewing company',72) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('slapshot brewing company',494) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mikerphone brewing',318) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('freetail brewing company',418) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('3 daughters brewing',520) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('red shedman farm brewery and hop...',225) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('appalachian mountain brewery',172) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('birdsong brewing company',379) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('union craft brewing',136) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('atwater brewery',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ale asylum',407) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('two brothers brewing company',93) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bent paddle brewing company',453) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bell''s brewery',519) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blue owl brewing',200) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('speakasy ales & lagers',298) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('black tooth brewing company',81) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hopworks urban brewery',201) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('epic brewing',395) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('new belgium brewing company',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sierra nevada brewing company',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('keweenaw brewing company',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('brewery terra firma',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('grey sail brewing company',155) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('kirkwood station brewing company',318) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('goose island brewing company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('broad brook brewing llc',463) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the lion brewery',338) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('madtree brewing company',554) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('jackie o''s pub & brewery',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('rhinegeist brewery',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('warped wing brewing company',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blackrocks brewery',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('catawba valley brewing company',158) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tröegs brewing company',191) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mission brewery',478) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('christian moerlein brewing company',473) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('west sixth brewing',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('coastal extreme brewing company',288) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('king street brewing company',177) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('beer works brewery',364) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lone tree brewing company',310) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('four string brewing company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('glabrous brewing company',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bonfire brewing company',435) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('thomas hooker brewing company',160) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('woodstock inn, station & brewery',130) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('renegade brewing company',86) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mother earth brew company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('black market brewing company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('vault brewing company',508) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('jailbreak brewing company',503) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('smartmouth brewing company',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('base camp brewing co.',91) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('alameda brewing',509) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('southern star brewing company',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('steamworks brewing company',146) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('horny goat brew pub',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cheboygan brewing company',83) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('center of the universe brewing c...',75) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ipswich ale brewery',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('griffin claw brewing company',149) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('karbach brewing company',336) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('uncle billy''s brewery and smokeh...',333) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('deep ellum brewing company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('real ale brewing company',268) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('straub brewery',129) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('shebeen brewing company',179) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('stevens point brewery',390) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('weston brewing company',163) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('southern prohibition brewing com...',544) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('minhas craft brewery',238) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pug ryan''s brewery',344) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hops & grains brewing company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sietsema orchards and cider mill',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('summit brewing company',357) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('core brewing & distilling company',220) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('independence brewing company',145) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cigar city brewing company',179) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('third street brewhouse',65) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('narragansett brewing company',455) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('grimm brothers brewhouse',436) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cisco brewers',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('angry minnow',339) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('platform beer company',300) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('odyssey beerwerks',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lonerider brewing company',173) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('oakshire brewing',525) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fort pitt brewing company',209) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tin roof brewing company',536) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('three creeks brewing',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('2 towns ciderhouse',105) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('caldera brewing company',175) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('greenbrier valley brewing company',341) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('phoenix ale brewery',137) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lumberyard brewing company',53) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('uinta brewing company',219) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('four peaks brewing company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('martin house brewing company',103) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('right brain brewery',248) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sly fox brewing company',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('round guys brewing',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('great crescent brewery',454) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('oskar blues brewery',57) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('boxcar brewing company',186) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('high hops brewery',117) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('crooked fence brewing company',126) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('everybody''s brewing',453) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('anderson valley brewing company',360) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fiddlehead brewing company',73) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('evil twin brewing',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('new orleans lager & ale brewing ...',440) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('spiteful brewing company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('rahr & sons brewing company',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('18th street brewery',547) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cambridge brewing company',95) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('carolina brewery',109) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('frog level brewing company',417) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wild wolf brewing company',199) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('coop ale works',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('seventh son brewing company',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('oasis texas brewing company',345) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('vander mill ciders',421) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('st. julian winery',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pedernales brewing company',180) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mother''s brewing',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('modern monks brewery',213) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('two beer brewing company',548) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('snake river brewing company',302) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('capital brewery',205) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('anthem brewing company',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('goodlife brewing co.',495) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('breakside brewery',56) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('goose island brewery company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('burnside brewing co.',469) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hop valley brewing company',99) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('worthy brewing company',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('occidental brewing company',377) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fearless brewing company',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('upland brewing company',502) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mehana brewing co.',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hawai''i nui brewing co.',117) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('people''s brewing company',267) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fort george brewery',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('branchline brewing company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('kalona brewing company',522) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('modern times beer',158) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('temperance beer company',230) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wisconsin brewing company',245) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('crow peak brewing company',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('grapevine craft brewery',317) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('buffalo bayou brewing company',115) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('texian brewing co.',260) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('orpheus brewing',167) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('forgotten boardwalk',290) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('laughing dog brewing company',252) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bozeman brewing company',351) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big choice brewing',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big storm brewing company',438) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('carton brewing company',226) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('midnight sun brewing company',484) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fat head''s brewery',67) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('refuge brewery',186) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('chatham brewing',472) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dc brau brewing company',240) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('geneva lake brewing company',290) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('rochester mills brewing company',237) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cape ann brewing company',159) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('borderlands brewing company',224) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('college street brewhouse and pub',168) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('joseph james brewing company',287) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('harpoon brewery',224) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('back east brewing company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('champion brewing company',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('devil''s backbone brewing company',481) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('newburgh brewing company',444) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wiseacre brewing company',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('golden road brewing',401) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('new republic brewing company',161) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('infamous brewing company',412) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('two henrys brewing company',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lift bridge brewing company',141) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lucky town brewing company',142) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('quest brewing company',187) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('creature comforts',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('half full brewery',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('southampton publick house',394) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('chapman''s brewing',116) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('barrio brewing company',240) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('santa cruz mountain brewing',549) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('frankenmuth brewery',527) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('meckley''s cidery',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('stillwater artisanal ales',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('finch''s beer company',525) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('south austin brewery',105) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bauhaus brew labs',169) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ozark beer company',553) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mountain town brewing company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('otter creek brewing',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the brewer''s art',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('denver beer company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ska brewing company',540) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tractor brewing company',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('peak organic brewing company',478) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cape cod beer',392) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('long trail brewing company',231) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('great raft brewing company',396) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('alaskan brewing company',364) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('notch brewing company',107) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the alchemist',326) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('three notch''d brewing company',82) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('portside brewery',145) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('otter creek brewing',386) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('montauk brewing company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('indeed brewing company',139) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('berkshire brewing company',314) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('foolproof brewing company',152) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('headlands brewing company',365) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bolero snort brewery',106) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('thunderhead brewing company',404) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('defiance brewing company',284) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('milwaukee brewing company',84) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('catawba island brewing',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('back forty beer company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('four corners brewing company',60) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('saint archer brewery',271) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('rogue ales',371) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hale''s ales',554) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tommyknocker brewery',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('baxter brewing company',146) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('northampton brewery',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('black shirt brewing company',211) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wachusett brewing company',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('widmer brothers brewing company',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hop farm brewing company',426) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('liquid hero brewery',265) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('matt brewing company',502) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('boston beer company',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('old forge brewing company',346) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('utah brewers cooperative',152) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('magic hat brewing company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blue hills brewery',464) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('night shift brewing',555) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('beach brewing company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('payette brewing company',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('brew bus brewing',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sockeye brewing company',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pine street brewery',109) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dirty bucket brewing company',390) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('jackalope brewing company',543) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('slanted rock brewing company',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('piney river brewing company',477) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cutters brewing company',488) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('iron hill brewery & restaurant',259) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('marshall wharf brewing company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('banner beer company',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dick''s brewing company',68) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('claremont craft ales',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('rivertown brewing company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('voodoo brewery',189) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('d.l. geary brewing company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pisgah brewing company',108) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('neshaminy creek brewing company',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('morgan street brewery',250) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('half acre beer company',395) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the just beer project',300) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the bronx brewery',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dead armadillo craft brewing',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('catawba brewing company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('la cumbre brewing company',212) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('david''s ale works',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the traveler beer company',58) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fargo brewing company',143) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big sky brewing company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('nebraska brewing company',475) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('uncle john''s fruit house winery',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wormtown brewery',171) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('due south brewing company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('palisade brewing company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('kelso beer company',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hardywood park craft brewery',487) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wolf hills brewing company',292) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lavery brewing company',62) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('manzanita brewing company',369) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fullsteam brewery',273) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('four horsemen brewing company',346) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hinterland brewery',469) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('central coast brewing company',344) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('westfield river brewing company',536) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('elevator brewing company',320) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('aslan brewing company',317) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('kulshan brewery',86) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pikes peak brewing company',155) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('manayunk brewing company',211) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('buckeye brewing',207) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('daredevil brewing company',551) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('noda brewing company',238) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('aviator brewing company',498) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wild onion brewing company',326) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hilliard''s beer',125) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mikkeller',463) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bohemian brewery',500) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('great river brewery',480) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mustang brewing company',529) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('airways brewing company',101) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('21st amendment brewery',387) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('eddyline brewery & restaurant',320) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pizza port brewing company',473) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sly fox brewing company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('spring house brewing company',297) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('7venth sun',465) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('astoria brewing company',403) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('maui brewing company',104) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('roughtail brewing company',376) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lucette brewing company',373) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bold city brewery',107) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('grey sail brewing of rhode island',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blue blood brewing company',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('swashbuckler brewing company',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blue mountain brewery',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('starr hill brewery',213) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('westbrook brewing company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('shipyard brewing company',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('revolution brewing',504) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('natian brewery',174) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('alltech''s lexington brewing company',270) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('oskar blues brewery (north carol...',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('orlison brewing company',73) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('breckenridge brewery',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('santa fe brewing company',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('miami brewing company',219) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('schilling & company',333) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hops & grain brewery',399) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('white flame brewing company',266) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ruhstaller beer company',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('saugatuck brewing company',331) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('moab brewery',303) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('macon beer company',356) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('amnesia brewing company',255) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wolverine state brewing company',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('red tank cider company',175) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cascadia ciderworks united',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fate brewing company',93) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lazy monk brewing',335) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bitter root brewing',201) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('10 barrel brewing company',460) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tamarack brewing company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('new england brewing company',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('seattle cider company',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('straight to ale',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('austin beerworks',256) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blue mountain brewery',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('coastal empire beer company',514) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('jack''s hard cider (hauser estate...',120) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('boulder beer company',497) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('coalition brewing company',405) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sanitas brewing company',112) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('gore range brewery',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('redstone meadery',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blue dog mead',288) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hess brewing company',456) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wynkoop brewing company',496) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ciderboys',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('armadillo ale works',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('roanoke railhouse brewery',534) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('schlafly brewing company',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('asher brewing company',456) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lost rhino brewing company',363) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('north country brewing company',460) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('seabright brewery',125) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('french broad brewery',220) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('angry orchard cider company',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('two roads brewing company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('southern oregon brewing company',248) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('brooklyn brewery',388) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the right brain brewery',454) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('kona brewing company',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('millking it productions',485) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pateros creek brewing company',505) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('o''fallon brewery',386) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('marble brewery',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big wood brewery',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('howard brewing company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('downeast cider house',165) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('swamp head brewery',486) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mavericks beer company',259) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tailgate beer',261) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('northwest brewing company',176) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dad & dude''s breweria',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('centennial beer company',435) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('denali brewing company',257) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('deschutes brewery',162) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sunken city brewing company',273) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lucette brewing company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the black tooth brewing company',137) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('kenai river brewing company',116) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('river north brewery',277) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('fremont brewing company',267) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('armstrong brewing company',485) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ac golden brewing company',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big bend brewing company',303) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('good life brewing company',265) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('engine 15 brewing',112) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('green room brewing',180) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('brindle dog brewing company',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('peace tree brewing company',218) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('terrapin brewing company',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pete''s brewing company',244) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('okoboji brewing company',324) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('crystal springs brewing company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('engine house 9',99) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tonka beer company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('red hare brewing company',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('hangar 24 craft brewery',314) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big elm brewing',163) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('good people brewing company',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('heavy seas beer',407) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('telluride brewing company',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('7 seas brewing company',400) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('confluence brewing company',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bale breaker brewing company',488) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('the manhattan brewing company',87) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mactarnahans brewing company',142) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('stillmank beer company',208) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('redhook brewery',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dock street brewery',160) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('blue point brewing company',439) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('tampa bay brewing company',59) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('devil''s canyon brewery',79) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('stone coast brewing company',271) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('broken tooth brewing company',275) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('seven brides brewery',495) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('newburyport brewing company',256) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dry dock brewing company',347) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cans bar and canteen',162) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sprecher brewing company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wildwood brewing company',337) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('high noon saloon and brewery',352) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('woodchuck hard cider',450) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sea dog brewing company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('oskar blues brewery',549) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('carolina beer & beverage',77) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('krebs brewing company (pete''s pl...',114) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('warbird brewing company',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mudshark brewing company',280) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('spilker ales',178) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wingman brewers',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('kettle house brewing company',430) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sherwood forest brewers',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('cottrell brewing',426) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('arctic craft brewery',434) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('monkey paw pub & brewery',383) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('crabtree brewing company',368) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('emerald city beer company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('butcher''s brewing',301) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('new south brewing company',262) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('big river brewing company',74) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('twisted pine brewing company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('flying dog brewery',188) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('uncommon brewers',58) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('aspen brewing company',57) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('triangle brewing company',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('bomb beer company',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('churchkey can company',399) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('intuition ale works',518) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('asheville brewing company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('northwoods brewpub',433) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('buckbean brewing company',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dolores river brewery',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('flat rock brewing company',506) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('abita brewing company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mammoth brewing company',349) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('harvest moon brewing company',81) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('grand canyon brewing company',297) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lewis and clark brewing company',448) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dundee brewing company',324) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('twin lakes brewing company',294) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mother earth brewing company',438) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('arcadia brewing company',205) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('angry minnow brewing company',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('great northern brewing company',521) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('pyramid breweries',177) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('lancaster brewing company',411) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('upstate brewing company',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('moat mountain smoke house & brew...',431) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('prescott brewing company',512) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mogollon brewing company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('wind river brewing company',388) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('silverton brewery',472) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('mickey finn''s brewery',427) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('covington brewhouse',461) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('dave''s brewfarm',74) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('ukiah brewing company',511) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('butternuts beer and ale',268) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(name,city_id) VALUES ('sleeping lady brewing company',7) ON CONFLICT DO NOTHING;
