CREATE TABLE IF NOT EXISTS beer.styles(
   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);

SELECT beer.trigger_creation('beer','styles','tr_b_styles');

INSERT INTO beer.styles(name) VALUES ('American Pale Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Pale Ale (APA)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American IPA') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Double / Imperial IPA') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Oatmeal Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Porter') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Saison / Farmhouse Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Belgian IPA') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Cider') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Baltic Porter') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Tripel') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Barleywine') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Winter Warmer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Fruit / Vegetable Beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Strong Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Black Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Belgian Dark Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Blonde Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Amber / Red Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Berliner Weissbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Brown Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Pale Wheat Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Belgian Strong Dark Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Kölsch') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Pale Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Amber / Red Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Barleywine') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Milk / Sweet Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('German Pilsener') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Pumpkin Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Belgian Pale Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Pilsner') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Wild Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Brown Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Altbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('California Common / Steam Beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Gose') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Cream Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Vienna Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Witbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Double / Imperial Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Munich Helles Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Schwarzbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Märzen / Oktoberfest') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Extra Special / Strong Bitter (ESB)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Rye Beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Euro Dark Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Hefeweizen') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Foreign / Export Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Other') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English India Pale Ale (IPA)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Czech Pilsener') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Strong Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Mead') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Euro Pale Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American White IPA') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Dortmunder / Export Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Irish Dry Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Scotch Ale / Wee Heavy') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Munich Dunkel Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Radler') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Bock') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Dark Mild Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Irish Red Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Rauchbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Bière de Garde') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Doppelbock') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Dunkelweizen') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Belgian Strong Pale Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Dubbel') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Quadrupel (Quad)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Russian Imperial Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Pale Mild Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Maibock / Helles Bock') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Herbed / Spiced Beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Adjunct Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Scottish Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Smoked Beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Light Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Abbey Single Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Roggenbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Kristalweizen') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Dark Wheat Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Old Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Double / Imperial Pilsner') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Flanders Red Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Keller Bier / Zwickel Bier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American India Pale Lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Shandy') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Wheat Ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('American Malt Liquor') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('English Bitter') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Chile Beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Grisette') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Flanders Oud Bruin') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Braggot') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('Low Alcohol Beer') ON CONFLICT DO NOTHING;
