CREATE TABLE IF NOT EXISTS beer.styles(
   id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);

SELECT beer.trigger_creation('beer','styles','tr_b_styles');

INSERT INTO beer.styles(name) VALUES ('american pale lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american pale ale (apa)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american ipa') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american double / imperial ipa') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('oatmeal stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american porter') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('saison / farmhouse ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('belgian ipa') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('cider') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('baltic porter') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('tripel') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american barleywine') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('winter warmer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('fruit / vegetable beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english strong ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american black ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('belgian dark ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american blonde ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american amber / red ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('berliner weissbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american brown ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american pale wheat ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('belgian strong dark ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('kölsch') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english pale ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american amber / red lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english barleywine') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('milk / sweet stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('german pilsener') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('pumpkin ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('belgian pale ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american pilsner') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american wild ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english brown ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('altbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('california common / steam beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('gose') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('cream ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('vienna lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('witbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american double / imperial stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('munich helles lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('schwarzbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('märzen / oktoberfest') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('extra special / strong bitter (esb)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('rye beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('euro dark lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('hefeweizen') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('foreign / export stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('other') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english india pale ale (ipa)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('czech pilsener') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american strong ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('mead') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('euro pale lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american white ipa') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('dortmunder / export lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('irish dry stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('scotch ale / wee heavy') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('munich dunkel lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('radler') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('bock') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english dark mild ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('irish red ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('rauchbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('bière de garde') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('doppelbock') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('dunkelweizen') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('belgian strong pale ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('dubbel') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('quadrupel (quad)') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('russian imperial stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english pale mild ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('maibock / helles bock') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('herbed / spiced beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american adjunct lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('scottish ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('smoked beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('light lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('abbey single ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('roggenbier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('kristalweizen') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american dark wheat ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english stout') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('old ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american double / imperial pilsner') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('flanders red ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('keller bier / zwickel bier') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american india pale lager') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('shandy') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('wheat ale') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('american malt liquor') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('english bitter') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('chile beer') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('grisette') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('flanders oud bruin') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('braggot') ON CONFLICT DO NOTHING;
INSERT INTO beer.styles(name) VALUES ('low alcohol beer') ON CONFLICT DO NOTHING;
